# Generated by Django 2.2 on 2021-02-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20210212_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='view_p',
            field=models.IntegerField(default=128),
        ),
    ]
