# Generated by Django 2.2 on 2021-02-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_category_view_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='view_p',
        ),
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
